package nz.ac.auckland.fitness.dto;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlRootElement;

/*
 * DTO Class used to represent an exercise involving sets
 */
@XmlRootElement(name="set_exercise")
@XmlAccessorType(XmlAccessType.FIELD)
public class SetExercise extends Exercise{
	
	@XmlElementWrapper(name="reps")
	@XmlElement(name="rep")
	private List<Integer> _reps;
	
	public SetExercise() {
		super();
		_reps = new ArrayList<Integer>();
	}
	
	/**
	 * Constructs a DTO SetExercise instance. This method is intended to be called
	 * by Web service clients when creating new SetExercise. The id field is not 
	 * required because it is generated by the Web service.
     *
	 */
	public SetExercise(String name, String description, List<Integer> reps) throws IllegalArgumentException {
		this(0,name,description,reps);
	}
	
	/**
	 * Constructs a DTO SetExercise instance. This method should NOT be called by 
	 * Web Service clients. It is intended to be used by the Web Service 
	 * implementation when creating a DTO SetExercise from a domain-model SetExercise 
	 * object.
	 */
	public SetExercise(int id, String name, String description, List<Integer> reps) {
		super(id, name, description);
		_reps = reps;
	}
	
	public void addSet(int rep) {
		_reps.add(rep);
	}
	
	// DEFAULT SETTERS AND GETTERS
	public List<Integer> get_reps() {
		return _reps;
	}

	public void set_reps(List<Integer> _reps) {
		this._reps = _reps;
	}
	// END DEFAULT SETTERS AND GETTERS
}
