package nz.ac.auckland.fitness.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

import org.joda.time.Duration;
import org.joda.time.LocalDate;

/*
 * DTO Class used to represent a completed workout
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
public class WorkoutRecord {

	@XmlElement(name = "id")
	private int _id;

	@XmlElement(name = "person")
	private String _person;

	@XmlElement(name = "workout_name")
	private String _workout_name;

	@XmlElement(name = "date")
	private LocalDate _date;

	@XmlElement(name = "duration")
	private Duration _duration;

	public WorkoutRecord() {
	}

	/**
	 * Constructs a DTO WorkoutRecord instance. This method is intended to be
	 * called by Web service clients when creating new WorkoutsRecord. The id
	 * field is not required because it is generated by the Web service.
	 * 
	 */
	public WorkoutRecord(String person, String workout_name, LocalDate date,
			Duration duration) {
		this(0, person, workout_name, date, duration);
	}

	/**
	 * Constructs a DTO WorkoutRecord instance. This method should NOT be called
	 * by Web Service clients. It is intended to be used by the Web Service
	 * implementation when creating a DTO WorkoutRecord from a domain-model
	 * WorkoutRecord object.
	 */
	public WorkoutRecord(int id, String person, String workout_name,
			LocalDate date, Duration duration) {
		_id = id;
		_person = person;
		_workout_name = workout_name;
		_date = date;
		_duration = duration;
	}

	// DEFAULT SETTERS AND GETTERS
	public int get_id() {
		return _id;
	}

	public void set_id(int _id) {
		this._id = _id;
	}
	
	public String get_person() {
		return _person;
	}

	public void set_person(String _person) {
		this._person = _person;
	}

	public String get_workout_name() {
		return _workout_name;
	}

	public void set_workout_name(String _workout_name) {
		this._workout_name = _workout_name;
	}

	public LocalDate get_date() {
		return _date;
	}

	public void set_date(LocalDate _date) {
		this._date = _date;
	}

	public Duration get_duration() {
		return _duration;
	}

	public void set_duration(Duration _duration) {
		this._duration = _duration;
	}
	// END DEFAULT SETTERS AND GETTERS

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((_date == null) ? 0 : _date.hashCode());
		result = prime * result
				+ ((_duration == null) ? 0 : _duration.hashCode());
		result = prime * result + _id;
		result = prime * result + ((_person == null) ? 0 : _person.hashCode());
		result = prime * result
				+ ((_workout_name == null) ? 0 : _workout_name.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		WorkoutRecord other = (WorkoutRecord) obj;
		if (_date == null) {
			if (other._date != null)
				return false;
		} else if (!_date.equals(other._date))
			return false;
		if (_duration == null) {
			if (other._duration != null)
				return false;
		} else if (!_duration.equals(other._duration))
			return false;
		if (_id != other._id)
			return false;
		if (_person == null) {
			if (other._person != null)
				return false;
		} else if (!_person.equals(other._person))
			return false;
		if (_workout_name == null) {
			if (other._workout_name != null)
				return false;
		} else if (!_workout_name.equals(other._workout_name))
			return false;
		return true;
	}

}
