package nz.ac.auckland.fitness.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

import org.joda.time.Duration;
import org.joda.time.LocalDate;

/*
 * DTO Class used to represent a completed workout
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
public class WorkoutRecord {

	@XmlElement(name = "id")
	private int _id;

	@XmlElement(name = "person_id")
	private int _person_id;

	@XmlElement(name = "workout_id")
	private int _workout_id;

	@XmlElement(name = "date")
	private LocalDate _date;

	@XmlElement(name = "duration")
	private Duration _duration;

	protected WorkoutRecord() {
	}

	/**
	 * Constructs a DTO WorkoutRecord instance. This method is intended to be
	 * called by Web service clients when creating new WorkoutsRecord. The id
	 * field is not required because it is generated by the Web service.
	 * 
	 */
	public WorkoutRecord(int person, int workout_id, LocalDate date,
			Duration duration) {
		this(0, person, workout_id, date, duration);
	}

	/**
	 * Constructs a DTO WorkoutRecord instance. This method should NOT be called
	 * by Web Service clients. It is intended to be used by the Web Service
	 * implementation when creating a DTO WorkoutRecord from a domain-model
	 * WorkoutRecord object.
	 */
	public WorkoutRecord(int id, int person, int workout_id, LocalDate date,
			Duration duration) {
		_id = id;
		_person_id = person;
		_workout_id = workout_id;
		_date = date;
		_duration = duration;
	}

	// DEFAULT SETTERS AND GETTERS
	public int get_id() {
		return _id;
	}

	public void set_id(int _id) {
		this._id = _id;
	}

	public int get_person_id() {
		return _person_id;
	}

	public void set_person_id(int _person_id) {
		this._person_id = _person_id;
	}

	public int get_workout_id() {
		return _workout_id;
	}

	public void set_workout_id(int _workout_id) {
		this._workout_id = _workout_id;
	}

	public LocalDate get_date() {
		return _date;
	}

	public void set_date(LocalDate _date) {
		this._date = _date;
	}

	public Duration get_duration() {
		return _duration;
	}

	public void set_duration(Duration _duration) {
		this._duration = _duration;
	}
	// END DEFAULT SETTERS AND GETTERS

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((_date == null) ? 0 : _date.hashCode());
		result = prime * result
				+ ((_duration == null) ? 0 : _duration.hashCode());
		result = prime * result + _person_id;
		result = prime * result + _workout_id;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		WorkoutRecord other = (WorkoutRecord) obj;
		if (_date == null) {
			if (other._date != null)
				return false;
		} else if (!_date.equals(other._date))
			return false;
		if (_duration == null) {
			if (other._duration != null)
				return false;
		} else if (!_duration.equals(other._duration))
			return false;
		if (_person_id != other._person_id)
			return false;
		if (_workout_id != other._workout_id)
			return false;
		return true;
	}

}
