package nz.ac.auckland.fitness.dto;

import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlRootElement;

import nz.ac.auckland.fitness.dto.Exercise;

import org.apache.commons.lang3.builder.HashCodeBuilder;

/*
 * DTO Class used to represent a Workout
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
public class Workout {
	
	@XmlElement(name="id")
	private int _id;
	
	@XmlElement(name="name")
	private String _name;
	
	@XmlElement(name="description")
	private String _description;
	
	@XmlElementWrapper(name="exercises")
	@XmlElement(name="exercise")
	private Set<Exercise> _exercises;
	
	protected Workout() {
		_exercises = new HashSet<Exercise>();
	}
	
	/**
	 * Constructs a DTO Workout instance. This method is intended to be called
	 * by Web service clients when creating new Workoutss. The id field is not 
	 * required because it is generated by the Web service.
     *
	 */
	public Workout(String name, String description, Set<Exercise> exercises) throws IllegalArgumentException {
		this(0,name,description,exercises);
	}
	
	/**
	 * Constructs a DTO Workout instance. This method should NOT be called by 
	 * Web Service clients. It is intended to be used by the Web Service 
	 * implementation when creating a DTO Workout from a domain-model Workout 
	 * object.
	 */
	public Workout(int id, String name, String description, Set<Exercise> exercises) {
		_id = id;
		_name = name;
		_description = description;
		_exercises = exercises;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (!(obj instanceof Workout))
            return false;
        if (obj == this)
            return true;

        Workout rhs = (Workout) obj;
        return this._name.equalsIgnoreCase(rhs._name);
	}
	
	@Override
	public int hashCode() {
		return new HashCodeBuilder(17, 31). 
	            append(_name).
	            toHashCode();
	}
	
	@Override
	public String toString() {
		return _name;
	}
	
	// DEFAULT SETTERS AND GETTERS
	public int get_id() {
		return _id;
	}

	public void set_id(int _id) {
		this._id = _id;
	}

	public String get_name() {
		return _name;
	}

	public void set_name(String _name) {
		this._name = _name;
	}

	public String get_description() {
		return _description;
	}

	public void set_description(String _description) {
		this._description = _description;
	}

	public Set<Exercise> get_exercises() {
		return _exercises;
	}

	public void set_exercises(Set<Exercise> _exercises) {
		this._exercises = _exercises;
	}
	// END DEFAULT SETTERS AND GETTERS

}
